import { existsSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Returns the public URL of the post audio generated by scripts/tts.js,
 * or undefined when public/audio/<slug>.mp3 does not exist at build time.
 */
export function getPostAudioSrc(slug: string): string | undefined {
  const audioFilePath = resolve(process.cwd(), "public/audio", `${slug}.mp3`);

  if (!existsSync(audioFilePath)) {
    return undefined;
  }

  return `/audio/${slug}.mp3`;
}
